version: '3.6'
services:
    ruby:
        image: license-audit:ruby
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
            args:
                img: ruby:2.5-alpine
                apks: 
        environment:
            env: ruby
        volumes:
            - apps:/audit/apps
            - reports:/audit/reports
            - build:/audit/build
    php:
        image: license-audit:php
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
            args:
                img: php:7.2-alpine
                apks: composer
        environment:
            env: php
        volumes:
            - apps:/audit/apps
            - reports:/audit/reports
            - build:/audit/build
    js:
        image: license-audit:js
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
            args:
                img: alpine
                apks: npm
        environment:
            env: js
        volumes:
            - apps:/audit/apps
            - reports:/audit/reports
            - build:/audit/build
    java:
        image: license-audit:java
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-android
            args:
                img: openjdk:8-alpine
                apks: gradle jq bash ruby-dev build-base libffi-dev curl-dev curl
        environment:
            env: java
        # command: tail -f /dev/null
        volumes:
            - apps:/audit/apps
            - reports:/audit/reports
            - build:/audit/build
volumes:
  apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/apps
  reports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/reports
  build:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/build