- - :ignore_group
  - devDependencies
  - :who:
    :why:
    :versions: []
    :when: 2020-11-20 17:23:10.865787500 Z
- - :approve
  - "expo"
  - :who: Tom
    :why: Used as a peer dependency as is MIT licensed
    :versions: []
    :when: 2020-11-20 16:00:00.000000000 Z
- - :approve
  - "react"
  - :who: Tom
    :why: Used as a peer dependency as is MIT licensed
    :versions: []
    :when: 2020-11-20 16:00:00.000000000 Z
- - :approve
  - "react-native"
  - :who: Tom
    :why: Used as a peer dependency as is MIT licensed
    :versions: []
    :when: 2020-11-20 16:00:00.000000000 Z
- - :approve
  - "spdx-exceptions"
  - :who: Tom
    :why: License audit tool required through lerna - Creative Commons 3.0
    :versions: []
    :when: 2020-11-19 16:00:00.000000000 Z
- - :approve
  - "spdx-license-ids"
  - :who: Tom
    :why: License audit tool required through lerna - Creative Commons 3.0
    :versions: []
    :when: 2020-11-19 16:00:00.000000000 Z