- - :approve
  - colored
  - :who: Tom
    :why: "No license declared in Gem, but MIT in Github: https://github.com/defunkt/colored/"
    :versions: ['1.2']
    :when: 2020-11-19 12:00:00.000000000 Z
- - :approve
  - rchardet
  - :who: Tom
    :why: "LGPL license required as part of git gem. No modification to source, so OK to use"
    :versions: ['1.8.0']
    :when: 2020-11-19 12:00:00.000000000 Z

