- - :approve
  - "consola"
  - :who: Steve
    :why: "MIT licensed, just no LICENSE file on Github"
    :versions: ['2.15.0']
    :when: 2019-''07-02 07:23:26.514774000 Z
- - :approve
  - "getenv"
  - :who: Steve
    :why: MIT licensed but repo has a LICENSE.md instead of LICENSE file
    :versions: []
    :when: 2021-04-21 16:00:00.000000000 Z
- - :approve
  - "xmldom"
  - :who: Steve
    :why: For this version you can choose either MIT or LGPL.  Latest version is solely MIT.
    :versions: ['0.1.31']
    :when: 2021-04-21 16:00:00.000000000 Z
- - :approve
  - "sax"
  - :who: Tom
    :why: BlueOak license still under discussion by Security, but this is used in React Native dependencies and so we can't avoid
    :versions: ['1.6.0', '1.6.1']
    :when: 2026-04-22 13:00:00.000000000 Z

