- - :ignore_group
  - sidekiq
  - :who: Steve
    :why: Group does not include runtime dependencies of the notifier
    :versions: []
    :when: 2021-04-14 17:34:34.662850000 Z
- - :ignore_group
  - test
  - :who: Steve
    :why: Group does not include runtime dependencies of the notifier
    :versions: []
    :when: 2021-04-14 17:34:35.248600000 Z
- - :ignore_group
  - coverage
  - :who: Steve
    :why: Group does not include runtime dependencies of the notifier
    :versions: []
    :when: 2021-04-14 17:34:35.843103000 Z
- - :ignore_group
  - rubocop
  - :who: Steve
    :why: Group does not include runtime dependencies of the notifier
    :versions: []
    :when: 2021-04-14 17:34:36.423089000 Z
