- - :approve
  - power_assert
  - :who: Tom
    :why: "Not detected by tool - BSD 2-clause license (https://github.com/k-tsj/power_assert/blob/v1.1.3/COPYING)"
    :versions: ['1.2.0']
    :when: 2019-12-09 15:00:00.000000000 Z

