- - :approve
  - webpack
  - :who: Tom
    :why: "Not detected by tool - MIT license (https://github.com/webpack/webpack/blob/v4.41.2/LICENSE)"
    :versions: []
    :when: 2019-12-09 15:00:00.000000000 Z