steps:
  - label: 'Ruby'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: ruby
  - label: 'PHP'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: php
  - label: 'JS'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: js