steps:
  - label: 'Ruby'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: ruby
    artifact_paths:
      - build/*
        reports/*
  - label: 'PHP'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: php
    artifact_paths:
      - build/*
        reports/*
  - label: 'JS'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: js
    artifact_paths:
      - build/*
        reports/*
  - label: 'Java'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: java
    artifact_paths:
      - build/*
        reports/*