steps:
  - label: 'Create report'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v2.6.0:
          run: ruby 
          command: ["bundle exec", "license_audit", "open_report"]
    artifact_paths: build/*