steps:
  - label: 'Ruby'
    if: build.env("FULL_BUILD") == "true"
    timeout_in_minutes: 240
    plugins:
      - docker-compose#v3.9.0:
          run: ruby
          env:
            - recent=2
    artifact_paths:
      - build/*.txt
      - reports/*.html

  - label: 'PHP'
    if: build.env("FULL_BUILD") == "true"
    timeout_in_minutes: 240
    plugins:
      - docker-compose#v3.9.0:
          run: php
          env:
            - recent=2
    artifact_paths:
      - build/*.txt
      - reports/*.html

  - label: 'JS'
    if: build.env("FULL_BUILD") == "true"
    timeout_in_minutes: 240
    plugins:
      - docker-compose#v3.9.0:
          run: js
          env:
            - recent=2
    artifact_paths:
      - build/*.txt
      - reports/*.html

  - label: 'Java'
    if: build.env("FULL_BUILD") == "true"
    timeout_in_minutes: 240
    plugins:
      - docker-compose#v3.9.0:
          run: java
          env:
            - recent=2
    artifact_paths:
      - build/*.txt
      - reports/*.html

  - label: 'Python'
    if: build.env("FULL_BUILD") == "true"
    timeout_in_minutes: 240
    plugins:
      - docker-compose#v3.9.0:
          run: python
          env:
            - recent=2
    artifact_paths:
      - build/*.txt
      - reports/*.html
