steps:
  - label: 'Ruby'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.0.3:
          run: ruby
    artifact_paths:
      - build/*
      - reports/*
  - label: 'PHP'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.0.3:
          run: php
    artifact_paths:
      - build/*
      - reports/*
  - label: 'JS'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.0.3:
          run: js
    artifact_paths:
      - build/*
      - reports/*
  - label: 'Java'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.0.3:
          run: java
    artifact_paths:
      - build/*
      - reports/*
  - label: 'Python'
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.0.3:
          run: python
    artifact_paths:
      - build/*
      - reports/*