ARG repo

FROM php:7.2-alpine

# RUN docker-php-ext-install dom

RUN apk update
RUN apk add --no-cache git build-base ncurses ncurses-dev openssh
RUN apk add --no-cache ruby ruby-bundler ruby-dev ruby-rdoc
RUN apk add --no-cache gradle
RUN apk add --no-cache nodejs npm
RUN apk add --no-cache php php-xml composer

RUN gem install bundler --version "=2.0.2"

COPY . /audit

RUN mkdir /root/.ssh/
ADD id_rsa /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

WORKDIR /audit

RUN bundle install

ENTRYPOINT ["bundle", "exec", "license_audit"]