ARG img=

FROM ${img}

ARG apks=

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update
RUN apt-get install -y git-core curl build-essential openssl libssl-dev
RUN apt-get install -y ruby ruby-bundler
RUN apt-get install -y ${apks}

RUN bundle config --global silence_root_warning 1

WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q
RUN unzip -q sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools" "build-tools;28.0.3"

ENV PATH="${PATH}:/sdk/platform-tools"
ENV ANDROID_HOME="/sdk/"

ENV ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"
ENV LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
ENV PATH="${PATH}:${ANDROID_NDK_HOME}"

ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"

COPY . /audit

WORKDIR /audit

RUN bundle install

ENV app=
ENV build=
ENV clean=
ENV dir=
ENV env=
ENV recent=
ENV wait=

CMD bundle exec license_audit audit --app=${app} \
                                    --build=${build} \
                                    --clean=${clean} \
                                    --dir=${dir} \
                                    --env=${env} \
                                    --recent=${recent} \
                                    --wait=${wait}