apps:
  # license-audit:                            # <- Unable to run on CI as this is a private repo
  #   repo: "bugsnag/license-audit"
  #   env: "ruby"
  #   build_command:
  #       - "bundle install"
  maze-runner:
    repo: "bugsnag/maze-runner"
    env: "ruby"
    build_command: 
        - "bundle install"
  bugsnag-ruby:
    repo: "bugsnag/bugsnag-ruby"
    env: "ruby"
    build_command: 
        - "bundle install --with coverage test rubocop sidekiq doc"
  bugsnag-dsym-upload:
    repo: "bugsnag/bugsnag-dsym-upload"
    env: "ruby"
    working_dir:
        - "tools/fastlane-plugin"
    build_command: 
        - "bundle install"
  bugsnag-api-ruby:
    repo: "bugsnag/bugsnag-api-ruby"
    env: "ruby"
    build_command: 
        - "bundle install"
  bugsnag-capistrano:
    repo: "bugsnag/bugsnag-capistrano"
    env: "ruby"
    build_command: 
        - "bundle install --with test"
  bugsnag-em:
    repo: "bugsnag/bugsnag-em"
    env: "ruby"
    build_command: 
        - "bundle install"
  bugsnag-js:
    repo: "bugsnag/bugsnag-js"
    env: "js"
    build_command:
        - "npm install"
    working_dir:
        - "."
        - "packages/*"
    license_finder_opts: "--enabled-package-managers npm"
  bugsnag-source-maps:
    repo: "bugsnag/bugsnag-source-maps"
    env: "js"
    build_command: 
        - "npm install"
    branch: "next"
  bugsnag-sourcemaps:
    repo: "bugsnag/bugsnag-sourcemaps"
    env: "js"
    build_command: 
        - "npm install"
  gulp-bugsnag:
    repo: "bugsnag/gulp-bugsnag"
    env: "js"
    build_command: 
        - "npm install"
  grunt-bugsnag:
    repo: "bugsnag/grunt-bugsnag"
    env: "js"
    build_command: 
        - "npm install"
  webpack-bugsnag-plugins:
    repo: "bugsnag/webpack-bugsnag-plugins"
    env: "js"
    build_command: 
        - "npm install"
  bugsnag-build-reporter-node:
    repo: "bugsnag/bugsnag-build-reporter-node"
    env: "js"
    build_command: 
        - "npm install"
  bugsnag-android:
    repo: "bugsnag/bugsnag-android"
    env: "java"
    build_command: 
        - "./gradlew build -x test"
    license_finder_opts: "--enabled-package-managers gradle"
  # bugsnag-android-gradle-plugin:           # <- Currently no licenses detected by tool
  #   repo: "bugsnag/bugsnag-android-gradle-plugin"
  #   env: "java"
  #   build_command: 
  #       - "./gradlew build -x test"
  #   license_finder_opts: "--enabled-package-managers gradle"
  bugsnag-java:
    repo: "bugsnag/bugsnag-java"
    env: "java"
    build_command: 
        - "./gradlew build -x test"
    license_finder_opts: "--enabled-package-managers gradle"
  bugsnag-php:
    repo: "bugsnag/bugsnag-php"
    env: "php"
    build_command: 
        - "composer install --no-interaction --prefer-dist"
  bugsnag-laravel:
    repo: "bugsnag/bugsnag-laravel"
    env: "php"
    build_command: 
        - "COMPOSER_MEMORY_LIMIT=-1 composer install"
    license_finder_opts: "--enabled-package-managers composer"
  bugsnag-symfony:
    repo: "bugsnag/bugsnag-symfony"
    env: "php"
    build_command: 
        - "composer install"
  # bugsnag-magento:                        # <- Currently unable to run with License Finder
  #   repo: "bugsnag/bugsnag-magento"
  #   env: "php"
  #   build_command: 
  #       - "composer install"
  bugsnag-silex:
    repo: "bugsnag/bugsnag-silex"
    env: "php"
    build_command: 
        - "composer install"
  bugsnag-wordpress:
    repo: "bugsnag/bugsnag-wordpress"
    env: "php"
    build_command: 
        - "composer install"
  bugsnag-psr-logger:
    repo: "bugsnag/bugsnag-psr-logger"
    env: "php"
    build_command: 
        - "composer install"
  bugsnag-python:
    repo: "bugsnag/bugsnag-python"
    env: "python"
    build_command: 
        - "pip install pip==20.0.2" # See https://github.com/pivotal/LicenseFinder/issues/714
        - "pip install -r dev_requirements.txt"
    license_finder_opts: "--pip-requirements-path=dev_requirements.txt --python-version=3"
  bugsnag-agent:
    repo: "bugsnag/bugsnag-agent"
    env: "python"
    build_command: 
        - "pip install pip==20.0.2" # See https://github.com/pivotal/LicenseFinder/issues/714
        - "pip install -r dev_requirements.txt"
    license_finder_opts: "--pip-requirements-path=dev_requirements.txt --python-version=3"